frontend:
    build:
      context: . # or ./frontend depending on your folder structure
      dockerfile: Dockerfile
      args:
        # This takes the value from your root .env and passes it to Dockerfile
        VITE_RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
        VITE_API_BASE_URL: "http://localhost:8080/api" 
    ports:
      - "5173:80" # Map host port 5173 to container port 80 (nginx)